### PR TITLE
Add .eslintcache to .gitignore

### PR DESCRIPTION
**Pull request by gabrieledarrigo**
### DESCRIPTION

Normally .eslintcache is generated to cache the linted files by eslint; 
It can be safely ignored, so I added .eslintcache to .gitignore and removed it from history.

### CODE REVIEW

**Comment by MarcoBuster** [comment]
I ignored that file in this commit 57cee0d81823913dcaf5cb1614be35befd965445 and removed it with 76aa6dcc5568281f7901872070af478826f7aba0. Thank you for your contribution but we already fixed it, sorry

**Comment by gabrieledarrigo** [comment]
> I ignored that file in this commit [57cee0d](https://github.com/StudentiUnimi/website/commit/57cee0d81823913dcaf5cb1614be35befd965445) and removed it with [76aa6dc](https://github.com/StudentiUnimi/website/commit/76aa6dcc5568281f7901872070af478826f7aba0). Thank you for your contribution but we already fixed it, sorry

Ok, no problem!
Just a question, is there any reason why .eslint configuration file isn't enclosed to the project?
I guess it's worth it to have it, so that code convention can be respected with ease.

**Comment by MarcoBuster** [comment]
We don't have a code convention now, maybe it's a thing we'll do in the future.

**Comment by gabrieledarrigo** [comment]
> We don't have a code convention now, maybe it's a thing we'll do in the future.

Yeah, need some help?

**Pull request closed without merging**
