### PR TITLE
Update dependencies and add npm-check package

### PR DESCRIPTION
**Pull request by gabrieledarrigo**
### DESCRIPTION

- Stick all dependencies versions to have more control over what's installed during build and deployment.
- Update all dependencies, both patch, minor, and major.
- Install [npm-check](https://www.npmjs.com/package/npm-check) package to eventually check and update al project's
dependencies.

I added a script to the package.json which can be used to check for outdated dependencies; to launch it just run the following command:

```
$ npm run check-update
```

It will invoke npm-check with the Interactive update shell.
The output is something like this:

image

### CODE REVIEW

**Comment by MarcoBuster** [comment]
Thank you for your PR. We just copied the files from the website folder to an upper level. Can you please resolve the git conflicts?

**Comment by MarcoBuster** [comment]
Make sure to fetch the last upstream commits before doing any change.

**Comment by gabrieledarrigo** [comment]
> Thank you for your PR. We just copied the files from the website folder to an upper level. Can you please resolve the git conflicts?

For sure!
Nice work, usually package.json and other application configuration files are in the root folder of the project 👍

**Comment by MarcoBuster** [comment]
package-lock.json is ignored, remove it

**Comment by gabrieledarrigo** [comment]
> package-lock.json is ignored, remove it

Ciao @MarcoBuster , why did you ignore it?
`package-lock.json` is meant to be included in the source code of the application; 
it represents the dependency tree of the project independently of any intermediate changes to `node_modules`.

Within `package-lock.json` the install process is repeatable across all environments. 
It also improves `npm i` performances, because the npm client can skip metadata resolutions for common packages of the tree that are already installed.

Here some moar information:

https://github.com/npm/cli/blob/release-6.14.7/docs/content/configuring-npm/package-lock-json.md

https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore

**Comment by MarcoBuster** [comment]
@gabrieledarrigo you're right, there is no reason to remove it.

**Comment by gabrieledarrigo** [comment]
> @gabrieledarrigo you're right, there is no reason to remove it.

Fantastic!
Let's merge this one?

**Comment by MarcoBuster** [comment]
Sure. Thank you!

**Pull request merged**
